### PR TITLE
Multi-arch build support

### PR DESCRIPTION
**Pull request by mzachar**
Improved multi-arch support in build.rs, it will now build on arm / aarch64 and link correct libraries

### CODE REVIEW

**Comment by adambezecny** [comment]
hi,

btw. what is your first name :) ? Is it Martin? Where are you from?

Regarding PR: what is the best platform to test this new build? Should it compile now on Raspberry Pi?

**Comment by mzachar** [comment]
You where close its Matej :) I'm from Slovakia

I was testing it on board with imx8 CPU from NXP but I do not see reason why it should not compile on Raspberry pi - ideal time to make some coffee while its compiling.

If you run into an issues just let me know

**Comment by adambezecny** [comment]
hi Matej,

I tried to compile your branch on my Raspberry Pi 3b and this is the result:

```
pi@raspberrypi:~/cognitive-services-speech-sdk-rs-matej/cognitive-services-speech-sdk-rs $ git status
On branch build
Your branch is up-to-date with 'origin/build'.
nothing to commit, working tree clean
pi@raspberrypi:~/cognitive-services-speech-sdk-rs-matej/cognitive-services-speech-sdk-rs $ cargo build
   Compiling cognitive-services-speech-sdk-rs v0.1.4 (/home/pi/cognitive-services-speech-sdk-rs-matej/cognitive-services-speech-sdk-rs)
error[E0308]: mismatched types
   --> src/audio/pull_audio_input_stream.rs:191:25
    |
191 |                         value as *mut i8,
    |                         ^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*mut u8`
               found raw pointer `*mut i8`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `cognitive-services-speech-sdk-rs`

To learn more, run the command again with --verbose.
pi@raspberrypi:~/cognitive-services-speech-sdk-rs-matej/cognitive-services-speech-sdk-rs $ git remote -v
origin	https://github.com/mzachar/cognitive-services-speech-sdk-rs.git (fetch)
origin	https://github.com/mzachar/cognitive-services-speech-sdk-rs.git (push)
pi@raspberrypi:~/cognitive-services-speech-sdk-rs-matej/cognitive-services-speech-sdk-rs $ cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a020d3
Serial		: 00000000dc1b37c4
pi@raspberrypi:~/cognitive-services-speech-sdk-rs-matej/cognitive-services-speech-sdk-rs $

```
I remember I was trying to compile it on RaspberryPi long long time ago and I got same error (if you actually try to compile my main branch you will get same error), unfortunately I do not remember any further details, this was long time ago.I can try investigate but this will take time, very busy these days. Or you can have a look:) When we add arm support raspberry should definitely work.

**Comment by mzachar** [comment]
A yes I fixed this as part of the SDK upgrade to 1.22.0 - I though it was changed with the new API.
I back ported the change from main branch. You can give it another try.

**Comment by adambezecny** [comment]
building now on both Windows WLS and Raspberry Pi. I want to do one more test, run all the examples but struggling to generate valid azure service key (did not do it long time :) ) so getting auth failure  when trying to call APIs. bear with me please. I just  created brand new Azure account, created instance of free tier cognitive speech service and trying to call samples with one of the keys, but not working. probably need to enable something else?  any advice since you probably use this stuff actively at the moment?

**Comment by adambezecny** [comment]
hi Matej,

ok so I resolved key issue (just defined in wrong region). I was able to run recognizer examples on Windows WLS but trying to run on Pi I am getting seg. fault:
```

pi@raspberrypi:~/cognitive-services-speech-sdk-rs-matej/cognitive-services-speech-sdk-rs $ cargo run --example recognizer
   Compiling cognitive-services-speech-sdk-rs v0.1.4 (/home/pi/cognitive-services-speech-sdk-rs-matej/cognitive-services-speech-sdk-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 40s
     Running `target/debug/examples/recognizer`
[2022-06-19T08:26:00Z INFO  recognizer::recognize_once_async_from_file] -------------------------------------------------
[2022-06-19T08:26:00Z INFO  recognizer::recognize_once_async_from_file] running recognize_once_async_from_file example...
[2022-06-19T08:26:00Z INFO  recognizer::recognize_once_async_from_file] -------------------------------------------------
Segmentation fault
pi@raspberrypi:~/cognitive-services-speech-sdk-rs-matej/cognitive-services-speech-sdk-rs $

```

**Comment by mzachar** [comment]
What Raspberry PI are you using? I just run the example with the  Raspberry PI 3 running "Raspberry Pi OS Lite 64bit" sucessfully

**Comment by adambezecny** [comment]
should be raspberry pi 3b. let me retry tomorrow, I can also give it a try on on r 400

**Comment by mzachar** [comment]
Can you post the result of the "uname -a" command on the raspberry?

**Comment by adambezecny** [comment]
first one:
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

**Comment by adambezecny** [comment]
second one (raspberry 400):
Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

**Comment by adambezecny** [comment]
btw Raspberry 3b still throws segmentation fault but this is what I just got on 400:
```

pi@raspberrypi:~/projects/cognitive-services-speech-sdk-rs $ cargo run --example recognizer
   Compiling cognitive-services-speech-sdk-rs v0.1.4 (/home/pi/projects/cognitive-services-speech-sdk-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 25.41s
     Running `target/debug/examples/recognizer`
[2022-06-25T09:46:53Z INFO  recognizer::recognize_once_async_from_file] -------------------------------------------------
[2022-06-25T09:46:53Z INFO  recognizer::recognize_once_async_from_file] running recognize_once_async_from_file example...
[2022-06-25T09:46:53Z INFO  recognizer::recognize_once_async_from_file] -------------------------------------------------
[2022-06-25T09:47:09Z INFO  recognizer::recognize_once_async_from_file] got recognition Ok(SpeechRecognitionResult { result_id: "0f414e4e259c4db584d2e7bc087daefe", reason: RecognizedSpeech, text: "Hello rust.", duration: "11500000", offset: "1300000" })
[2022-06-25T09:47:09Z INFO  recognizer::recognize_once_async_from_file] example finished!
[2022-06-25T09:47:10Z INFO  recognizer::continuous_recognition_from_file] ---------------------------------------------------
[2022-06-25T09:47:10Z INFO  recognizer::continuous_recognition_from_file] running continuous_recognition_from_file example...
[2022-06-25T09:47:10Z INFO  recognizer::continuous_recognition_from_file] ---------------------------------------------------
[2022-06-25T09:47:10Z INFO  recognizer::helpers] >set_session_started_cb SessionEvent { session_id: "6fdeec82f11741f4937e0cbf1bae3fa4" }
[2022-06-25T09:47:11Z INFO  recognizer::helpers] >set_speech_start_detected_cb RecognitionEvent { base: SessionEvent { session_id: "6fdeec82f11741f4937e0cbf1bae3fa4" }, offset: 4400000 }
[2022-06-25T09:47:11Z INFO  recognizer::helpers] >set_recognizing_cb "turn"
[2022-06-25T09:47:11Z INFO  recognizer::helpers] >set_recognizing_cb "turn on the lamp"
[2022-06-25T09:47:11Z INFO  recognizer::helpers] >set_recognized_cb SpeechRecognitionEvent { base: RecognitionEvent { base: SessionEvent { session_id: "6fdeec82f11741f4937e0cbf1bae3fa4" }, offset: 4400000 }, result: SpeechRecognitionResult { result_id: "2c48cd70225b416590ae08fa86db001a", reason: RecognizedSpeech, text: "Turn on the lamp.", duration: "10800000", offset: "4400000" } }
[2022-06-25T09:47:11Z INFO  recognizer::helpers] >set_speech_end_detected_cb RecognitionEvent { base: SessionEvent { session_id: "6fdeec82f11741f4937e0cbf1bae3fa4" }, offset: 19300000 }
[2022-06-25T09:47:11Z INFO  recognizer::helpers] >set_canceled_cb SpeechRecognitionCanceledEvent { base: SpeechRecognitionEvent { base: RecognitionEvent { base: SessionEvent { session_id: "6fdeec82f11741f4937e0cbf1bae3fa4" }, offset: 0 }, result: SpeechRecognitionResult { result_id: "3596ae3dae724ab5a633090da7027b71", reason: Canceled, text: "", duration: "0", offset: "0" } }, reason: EndOfStream, error_code: NoError, error_details: "�\u{6}��p\u{4}��L�Ͼ-" }
[2022-06-25T09:47:11Z INFO  recognizer::helpers] >set_session_stopped_cb SessionEvent { session_id: "6fdeec82f11741f4937e0cbf1bae3fa4" }
[2022-06-25T09:47:20Z INFO  recognizer::continuous_recognition_from_file] example finished!
corrupted size vs. prev_size
Neúspěšně ukončen (SIGABRT)
pi@raspberrypi:~/projects/cognitive-services-speech-sdk-rs $ 
pi@raspberrypi:~/projects/cognitive-services-speech-sdk-rs $ 
pi@raspberrypi:~/projects/cognitive-services-speech-sdk-rs $ 
pi@raspberrypi:~/projects/cognitive-services-speech-sdk-rs $ 
pi@raspberrypi:~/projects/cognitive-services-speech-sdk-rs $ cargo run --example recognizer
   Compiling cognitive-services-speech-sdk-rs v0.1.4 (/home/pi/projects/cognitive-services-speech-sdk-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 12.92s
     Running `target/debug/examples/recognizer`
[2022-06-25T09:49:35Z INFO  recognizer::recognize_once_async_from_file] -------------------------------------------------
[2022-06-25T09:49:35Z INFO  recognizer::recognize_once_async_from_file] running recognize_once_async_from_file example...
[2022-06-25T09:49:35Z INFO  recognizer::recognize_once_async_from_file] -------------------------------------------------
[2022-06-25T09:49:38Z INFO  recognizer::recognize_once_async_from_file] got recognition Ok(SpeechRecognitionResult { result_id: "6038abc1a9c34fefabb5238ea6369fc9", reason: RecognizedSpeech, text: "Hello rust.", duration: "11500000", offset: "1300000" })
[2022-06-25T09:49:38Z INFO  recognizer::recognize_once_async_from_file] example finished!
corrupted size vs. prev_size
Neúspěšně ukončen (SIGABRT)
pi@raspberrypi:~/projects/cognitive-services-speech-sdk-rs $ uname -a
Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux
pi@raspberrypi:~/projects/cognitive-services-speech-sdk-rs $ cargo run --example recognizer
   Compiling cognitive-services-speech-sdk-rs v0.1.4 (/home/pi/projects/cognitive-services-speech-sdk-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 12.71s
     Running `target/debug/examples/recognizer`
[2022-06-25T09:51:52Z INFO  recognizer::recognize_once_async_from_file] -------------------------------------------------
[2022-06-25T09:51:52Z INFO  recognizer::recognize_once_async_from_file] running recognize_once_async_from_file example...
[2022-06-25T09:51:52Z INFO  recognizer::recognize_once_async_from_file] -------------------------------------------------
[2022-06-25T09:51:53Z INFO  recognizer::recognize_once_async_from_file] got recognition Ok(SpeechRecognitionResult { result_id: "fa745f5a919a4842a13fe743ba97a8f8", reason: RecognizedSpeech, text: "Hello rust.", duration: "11500000", offset: "1300000" })
[2022-06-25T09:51:53Z INFO  recognizer::recognize_once_async_from_file] example finished!
Neoprávněný přístup do paměti (SIGSEGV)
pi@raspberrypi:~/projects/cognitive-services-speech-sdk-rs $

```

**Comment by mzachar** [comment]
So both of them are **32bit** armv7 systems which are Tier 2 rust supported targets ("guaranteed to build").

Also it looks like Microsoft might have an issue in their SDK as well: (it has very similar symptoms)
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/893

Which their are not going to investigate as it is "not supported" platform :)

I tried to run the example on the 32bit armv7 image and the only thing that works is if you run just "continuous_recognition_from_file::run_example().await;" and comment all others out. But as soon as some callback are introduced you get "segfault" or "corrupted size vs. prev_size".

However when I tested it with Raspberry PI using 64bit (aarch64) image the examples run just fine.
Try to use - **64bit** - raspberry pi image e.g.:
https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2022-04-07/2022-04-04-raspios-bullseye-arm64-lite.img.xz

**Comment by adambezecny** [comment]
ok, so after little bit of thinking I have manged to dig out from my table raspberry pi 4 with 64bit OS :) and it works! I was finally able to run all examples, no seg. fault his time. Bear with me just a little bit longer Matej, I will try to test just a little bit more, but this is on good way to be merged. thank you for all your time and effort so far!

**Review by adambezecny — APPROVED** [review]
lgtm

**Comment by adambezecny** [comment]
hi,

sorry for delay, I was off this week. Did not have time for additional test but I think it works. So let's merge and proceed with embedded speech config PR. thanks!

**Pull request merged**
